CREATE TABLE users (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50 CHAR) NOT NULL,
    email VARCHAR2(255 CHAR) NOT NULL,
    password VARCHAR2(255 CHAR) NOT NULL,
    role VARCHAR2(20 CHAR) DEFAULT 'USER' NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE refresh_tokens (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    token_hash VARCHAR2(64 CHAR) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT ck_refresh_tokens_revoked CHECK (revoked IN (0, 1))
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);
